# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hbase-k8s.master.fullname" . }}
  labels:
    app: {{ template "hbase-k8s.master.name" . }}
    chart: {{ template "hbase-k8s.subchart" . }}
    release: {{ .Release.Name }}
  annotations:
    # TODO: Deprecated. Replace tolerate-unready-endpoints with
    # v1.Service.PublishNotReadyAddresses.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8080
      name: restapi
    - port: 9090
      name: thriftapi
    - port: 16000
      name: master
    - port: 16010
      name: masterinfo
  clusterIP: None
  selector:
    app: {{ template "hbase-k8s.master.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "hbase-k8s.master.fullname" . }}
  labels:
    app: {{ template "hbase-k8s.master.name" . }}
    chart: {{ template "hbase-k8s.subchart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "hbase-k8s.master.name" . }}
      release: {{ .Release.Name }}
  minAvailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "hbase-k8s.master.fullname" . }}
  labels:
    app: {{ template "hbase-k8s.master.name" . }}
    chart: {{ template "hbase-k8s.subchart" . }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "hbase-k8s.master.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "hbase-k8s.master.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hbase-k8s.master.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
    spec:
      {{- if .Values.hostNetworkEnabled }}
      # Use hostNetwork so datanodes connect to namenode without going through an overlay network
      # like weave. Otherwise, namenode fails to see physical IP address of datanodes.
      # Disabling this will break data locality as namenode will see pod virtual IPs and fails to
      # equate them with cluster node physical IPs associated with data nodes.
      # We currently disable this only for CI on minikube.
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      dnsPolicy: ClusterFirst
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- else if .Values.global.defaultAffinityEnabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - {{ template "hbase-k8s.master.name" . }}
                  - key: "release"
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: hbase-master
          image: pierrezemb/hbase-docker:distributed-1.3.1-hadoop-2.7.3
          env:
            - name: HADOOP_CUSTOM_CONF_DIR
              value: /etc/hadoop-custom-conf
            - name: HBASE_CUSTOM_CONF_DIR
              value: /etc/hbase-custom-conf
            # Used by the start script below.
            - name: MY_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ['/bin/sh', '-c']
          # The start script is provided by a config map.
          args:
            - /etc/hbase-custom-conf/bootstrap.sh;while true;do echo hello;sleep 10000;done
          ports:
            - containerPort: 8080
              name: restapi
            - containerPort: 9090
              name: thriftapi
            - containerPort: 16000
              name: master
            - containerPort: 16010
              name: masterinfo
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: 16010
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 16010
            initialDelaySeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: hbase-config
              mountPath: /etc/hbase-custom-conf
              readOnly: true
            - name: hdfs-config
              mountPath: /etc/hadoop-custom-conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: hbase-config
          configMap:
            name: {{ template "hbase-k8s.config.fullname" . }}
            defaultMode: 0744
        - name: hdfs-config
          configMap:
            name: {{ template "hdfs-k8s.config.fullname" . }}
      {{- if .Values.global.podSecurityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.global.podSecurityContext.fsGroup }}
  {{- end }}
