## ------------------------------------------------------------------------------
## nginx-ingress:
## ------------------------------------------------------------------------------
nginx-ingress:
  controller:
    replicaCount: 1
    hostNetwork: true
    nodeSelector:
      node-role.kubernetes.io/edge: ''
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nginx-ingress
                - key: component
                  operator: In
                  values:
                    - controller
            topologyKey: kubernetes.io/hostname
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: PreferNoSchedule
  defaultBackend:
    image:
      repository: registry.cn-hangzhou.aliyuncs.com/lusifeng/defaultbackend-amd64
      tag: "1.5"
    nodeSelector:
      node-role.kubernetes.io/edge: ''
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: PreferNoSchedule
  rbac:
    create: true
  tcp:
    9090: "default/hbase-k8s-thriftserver:9090"
    2181: "default/hdfs-k8s-zookeeper:2181"
## ------------------------------------------------------------------------------
## hbase-config-k8s:
## ------------------------------------------------------------------------------
hbase-config-k8s:
  ## Custom hbase config keys passed to the hbase configmap as extra keys.
  customHbaseConfig:
    hbaseSite: {}
      ## Set config key and value pairs, e.g.
      # hbase.cluster.distributed: true

## ------------------------------------------------------------------------------
## hbase-master-k8s:
## ------------------------------------------------------------------------------
hbase-master-k8s:

  resources:
    requests:
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

  ## Node labels and tolerations for pod assignment
  nodeSelector:
    hbase-master-selector: hbase-master
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hbase-regionserver-k8s:
## ------------------------------------------------------------------------------
hbase-regionserver-k8s:

  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  ## Node labels and tolerations for pod assignment
  nodeSelector: []
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hbase-restserver-k8s:
## ------------------------------------------------------------------------------
hbase-restserver-k8s:

  resources:
    requests:
      memory: "256Mi"
      cpu: "10m"
    limits:
      memory: "1024Mi"
      cpu: "500m"

## ------------------------------------------------------------------------------
## hbase-thriftserver-k8s:
## ------------------------------------------------------------------------------
hbase-thriftserver-k8s:

  replicaCount: 2

  resources:
    requests:
      memory: "256Mi"
      cpu: "10m"
    limits:
      memory: "1024Mi"
      cpu: "500m"

## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ##
  hostNetworkEnabled: true

  hbaseRootdir: hdfs://hdfs-k8s/hbase

  hdfsConfigMap: hdfs-k8s-config

  ## Override zookeeper quorum address.
  zookeeperQuorumOverride: hdfs-k8s-zookeeper-0.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-1.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-2.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181

  ## How many master nodes to launch as a quorum.
  masterQuorumSize: 2

  ## How many regionServer nodes to launch as a quorum.
  regionserverQuorumSize: 3

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for high availability. Enabled by default.
  hbase: true
