## ------------------------------------------------------------------------------
## hbase-config-k8s:
## ------------------------------------------------------------------------------
hbase-config-k8s:
  ## Custom hbase config keys passed to the hbase configmap as extra keys.
  customHbaseConfig:
    hbaseSite: {}
      ## Set config key and value pairs, e.g.
      # hbase.cluster.distributed: true

## ------------------------------------------------------------------------------
## hbase-master-k8s:
## ------------------------------------------------------------------------------
hbase-master-k8s:

  ## Whether or not to use hostNetwork in namenode pods. Disabling this will break
  ## data locality as namenode will see pod virtual IPs and fails to equate them with
  ## cluster node physical IPs associated with data nodes.
  ## We currently disable this only for CI on minikube.
  hostNetworkEnabled: true

  resources:
    requests:
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

  ## Node labels and tolerations for pod assignment
  nodeSelector:
    hbase-master-selector: hbase-master
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hbase-regionserver-k8s:
## ------------------------------------------------------------------------------
hbase-regionserver-k8s:

  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  ## Node labels and tolerations for pod assignment
  nodeSelector: []
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ## Whether or not to expect namenodes in the HA setup.
  namenodeHAEnabled: true

  hbaseRootdir: hdfs://hdfs-k8s/hbase

  hdfsConfigMap: hdfs-k8s-config

  ## Override zookeeper quorum address.
  zookeeperQuorumOverride: hdfs-k8s-zookeeper-0.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-1.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-2.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181

  ## How many regionServer nodes to launch as a quorum.
  regionserverQuorumSize: 3

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for high availability. Enabled by default.
  hbase: true
