## ------------------------------------------------------------------------------
## hbase-config-k8s:
## ------------------------------------------------------------------------------
hbase-config-k8s:
  ## Custom hbase config keys passed to the hbase configmap as extra keys.
  customHbaseConfig:
    hbaseSite: {}
      ## Set config key and value pairs, e.g.
      # hbase.cluster.distributed: true

## ------------------------------------------------------------------------------
## hbase-master-k8s:
## ------------------------------------------------------------------------------
hbase-master-k8s:

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m

  ## Node labels and tolerations for pod assignment
  nodeSelector:
    hbase-master-selector: hbase-master
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hbase-regionserver-k8s:
## ------------------------------------------------------------------------------
hbase-regionserver-k8s:

  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m

  ## Node labels and tolerations for pod assignment
  nodeSelector: []
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hbase-restserver-k8s:
## ------------------------------------------------------------------------------
hbase-restserver-k8s:

  service:
    type: ClusterIP
    externalPort: 8080

    ## This allows an override of the heapster service name
    ## Default: {{ .Chart.Name }}
    ##
    # nameOverride:

    # LoadBalancerSourcesRange is a list of allowed CIDR values, which are combined with ServicePort to
    # set allowed inbound rules on the security group assigned to the master load balancer
    # loadBalancerSourceRanges: []

    ## Hbase REST Service annotations
    ##
    ## For GCE ingress, the following annotation is required:
    ## service.alpha.kubernetes.io/app-protocols: '{"http":"HTTP"}' if enableInsecureLogin=true
    annotations: {}

    ## Here labels can be added to the Hbase REST Service
    ##
    labels: {}
    # kubernetes.io/name: "Hbase REST"

  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 100m

  ingress:
    ## If true, Hbase REST Ingress will be created.
    ##
    enabled: true

    ## Hbase REST Ingress annotations
    ##
    ## Add custom labels
    # labels:
    #   key: value
    annotations:
       kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: 'true'
    ## If you plan to use TLS backend with enableInsecureLogin set to false
    ## (default), you need to uncomment the below.
    ## If you use ingress-nginx < 0.21.0
    #   nginx.ingress.kubernetes.io/secure-backends: "true"
    ## if you use ingress-nginx >= 0.21.0
    #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"


    ## Hbase REST Ingress paths
    ##
    paths:
      - /
    #  - /*

    ## Hbase REST Ingress hostnames
    ## Must be provided if Ingress is enabled
    ##
    hosts:
       - hbase-k8s.fcbox.com

    ## Hbase REST Ingress TLS configuration
    ## Secrets must be manually created in the namespace
    ##
    # tls:
    #   - secretName: kubernetes-dashboard-tls
    #     hosts:
    #       - kubernetes-dashboard.domain.com

## ------------------------------------------------------------------------------
## hbase-thriftserver-k8s:
## ------------------------------------------------------------------------------
hbase-thriftserver-k8s:

  replicaCount: 2

  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 100m

## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ##
  hostNetworkEnabled: true

  hbaseRootdir: hdfs://hdfs-k8s/hbase

  hdfsConfigMap: hdfs-k8s-config

  ## Override zookeeper quorum address.
  zookeeperQuorumOverride: hdfs-k8s-zookeeper-0.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-1.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181,hdfs-k8s-zookeeper-2.hdfs-k8s-zookeeper-headless.default.svc.cluster.local:2181

  ## How many master nodes to launch as a quorum.
  masterQuorumSize: 2

  ## How many regionServer nodes to launch as a quorum.
  regionserverQuorumSize: 3

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for high availability. Enabled by default.
  hbase: true
