apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "hbase-k8s.fullname" . }}
  labels:
    app: {{ template "hbase-k8s.name" . }}
    chart: {{ template "hbase-k8s.subchart" . }}
    release: {{ .Release.Name }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hbase-k8s.fcbox.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "hbase-k8s.restserver.fullname" . }}
              servicePort: 8080